"""
Financial Fraud Detection API — Model V1
=========================================

Generated by notebooks/05_model_deployment.ipynb (Phase 5). Do not edit by hand; re-run the
notebook if the feature pipeline or model artifacts change.

Pipeline implemented here:

    Raw transaction (HTTP request)
        -> Pydantic validation
        -> update/read per-account historical state (in-memory, dev-only - see AccountState)
        -> compute the same candidate features Phase 3 defines
        -> select the EXACT feature names/order Model V1 was trained on (model_v1_metadata.json)
        -> XGBoost Model V1 .predict_proba()
        -> fraud_probability, risk_score, risk_level, model_version

CRITICAL LEAKAGE GUARD: `isFraud` is never accepted as API input, and post-transaction fields
(`newbalanceOrig`, `newbalanceDest`) are accepted only for compatibility with raw PaySim CSV rows
used in testing/simulation - they are NEVER read by the feature pipeline below, because Phase 3's
leakage audit marked every feature derived from them UNSAFE and Model V1 was not trained on them.
"""

from __future__ import annotations

import json
import logging
import math
from copy import deepcopy
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field, field_validator
from xgboost import XGBClassifier

logger = logging.getLogger("fraud_api")
logging.basicConfig(level=logging.INFO)

# ---------------------------------------------------------------------------------------------
# Project paths - resolved from this file's own location so the API works regardless of the
# working directory it is started from (src/api/app.py -> parents[2] is the project root).
# ---------------------------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[2]
MODEL_PATH = PROJECT_ROOT / "models" / "xgboost_model_v1.json"
METADATA_PATH = PROJECT_ROOT / "models" / "model_v1_metadata.json"
THRESHOLD_PATH = PROJECT_ROOT / "models" / "model_v1_threshold.json"
FE_SUMMARY_PATH = PROJECT_ROOT / "reports" / "feature_engineering_summary.json"
LOG_PATH = PROJECT_ROOT / "reports" / "model_v1_predictions_log.jsonl"

# ---------------------------------------------------------------------------------------------
# Load model + frozen configuration ONCE, at import time (not per-request).
# uvicorn imports this module a single time when the worker process starts, so `model` and the
# constants below are built once and reused for every request that process handles.
# ---------------------------------------------------------------------------------------------
for _p in (MODEL_PATH, METADATA_PATH, THRESHOLD_PATH, FE_SUMMARY_PATH):
    if not _p.is_file():
        raise FileNotFoundError(f"Required artifact not found: {_p}. Run notebooks 03/04 (and 05) before starting the API.")

model = XGBClassifier()
model.load_model(str(MODEL_PATH))

with open(METADATA_PATH, encoding="utf-8") as _fh:
    METADATA = json.load(_fh)
with open(THRESHOLD_PATH, encoding="utf-8") as _fh:
    THRESHOLD_INFO = json.load(_fh)
with open(FE_SUMMARY_PATH, encoding="utf-8") as _fh:
    FE_SUMMARY = json.load(_fh)

FINAL_FEATURES: list[str] = METADATA["feature_names"]           # exact names, exact order
MODEL_VERSION: str = METADATA["model_version"]
CLASSIFICATION_THRESHOLD: float = THRESHOLD_INFO["selected_threshold"]
RISK_LEVELS: dict = THRESHOLD_INFO["risk_levels"]                # display bands, independent of CLASSIFICATION_THRESHOLD
FE_PARAMS: dict = FE_SUMMARY["frozen_parameters_fitted_on_training_period"]
TYPE_CATEGORIES: list[str] = FE_PARAMS["type_categories"]
WINDOWS = tuple(FE_PARAMS["windows"])
SUM_WINDOWS = tuple(FE_PARAMS["sum_windows"])
NEWCP_WINDOWS = tuple(FE_PARAMS["newcp_windows"])
HOURS_PER_DAY = FE_PARAMS["hours_per_day"]
MAX_WINDOW = max(WINDOWS)
LARGE_AMOUNT_THRESHOLD = FE_PARAMS["large_amount_threshold"]
RETAIN_FLAG_FEATURE = bool(FE_PARAMS.get("retain_flag_feature", False))

logger.info("Model V1 loaded. %d expected features. Classification threshold=%.2f",
           len(FINAL_FEATURES), CLASSIFICATION_THRESHOLD)

# ---------------------------------------------------------------------------------------------
# Feature engineering - mirrors notebooks/03_feature_engineering.ipynb EXACTLY (same formulas,
# same frozen constants). Only the features that are SAFE or POTENTIAL_RISK per the Phase 3
# leakage audit are computed here; nothing derived from newbalanceOrig/newbalanceDest exists
# below, by construction (those columns are simply never read).
# ---------------------------------------------------------------------------------------------

def safe_divide(numerator: float, denominator: float) -> float:
    """Returns NaN (not inf, not 0) when the denominator is not strictly positive."""
    if denominator is None or denominator <= 0 or numerator is None:
        return float("nan")
    return numerator / denominator


def create_temporal_features(step: int) -> dict:
    hour = (step - 1) % HOURS_PER_DAY
    return {
        "hour_of_day": hour,
        "hour_sin": math.sin(2 * math.pi * hour / HOURS_PER_DAY),
        "hour_cos": math.cos(2 * math.pi * hour / HOURS_PER_DAY),
        "time_period_bin": hour // 6,
        "day_index": (step - 1) // HOURS_PER_DAY,
    }


def create_amount_features(amount: float, old_balance_orig: float, old_balance_dest: float) -> dict:
    return {
        "amount": amount,
        "log_amount": math.log1p(max(amount, 0.0)),
        "is_zero_amount": int(amount == 0),
        "is_large_amount": int(amount >= LARGE_AMOUNT_THRESHOLD),
        "amount_to_sender_balance_ratio": safe_divide(amount, old_balance_orig),
        "amount_ge_sender_balance": int((amount >= old_balance_orig - FE_PARAMS["tolerance"]) and old_balance_orig > 0),
        "sender_remaining_if_debited": old_balance_orig - amount,
        "amount_to_dest_balance_ratio": safe_divide(amount, old_balance_dest),
    }


def create_balance_features(old_balance_orig: float, old_balance_dest: float) -> dict:
    """PRE-transaction balance features only. newbalanceOrig/newbalanceDest are never used here."""
    return {
        "sender_balance_before": old_balance_orig,
        "sender_balance_zero_before": int(old_balance_orig == 0),
        "dest_balance_before": old_balance_dest,
        "dest_balance_zero_before": int(old_balance_dest == 0),
    }


def encode_transaction_type(txn_type: str) -> dict:
    """One-hot encoding using the frozen category list fitted in Phase 3."""
    return {f"type_{cat}": int(txn_type == cat) for cat in TYPE_CATEGORIES}



class AccountState:
    """
    In-memory, per-account historical state for the sender and destination roles.

    *** DEVELOPMENT / DEMO MECHANISM ONLY ***
    This is a plain Python dict living inside one running API process. It is intentionally simple
    for Phase 5: state is lost on restart, and it does not scale across multiple API instances.
    A later phase (Kafka + Spark Structured Streaming, stateful processing keyed by account) will
    replace this with a durable, shared state store. The FEATURE DEFINITIONS implemented here are
    exactly what that future stateful job must also compute - only the storage mechanism will change.

    Guarantee: for a transaction at step t, only events strictly BEFORE this call are ever read.
    The state is updated with the current transaction only AFTER its features are computed.
    """

    def __init__(self):
        self._state = {"sender": {}, "dest": {}}
        self._pairs: set[tuple[str, str]] = set()

    def reset(self) -> None:
        """Clear process-local history before a deterministic replay or demo run."""
        self._state = {"sender": {}, "dest": {}}
        self._pairs = set()

    @staticmethod
    def _new_account() -> dict:
        return {"count": 0, "total": 0.0, "max": float("nan"), "last_step": None, "uniq": 0, "events": deque()}

    def _role_features(self, role: str, acct: dict, step: int) -> dict:
        while acct["events"] and acct["events"][0][0] <= step - MAX_WINDOW:
            acct["events"].popleft()
        feats = {
            f"{role}_prev_txn_count": acct["count"],
            f"{role}_prev_total_amount": acct["total"],
            f"{role}_prev_mean_amount": (acct["total"] / acct["count"]) if acct["count"] else float("nan"),
            f"{role}_prev_max_amount": acct["max"],
            f"{role}_prev_unique_counterparties": acct["uniq"],
            f"{role}_hours_since_prev_txn": (step - acct["last_step"]) if acct["count"] else float("nan"),
        }
        for w in WINDOWS:
            feats[f"{role}_txn_count_last_{w}h"] = sum(1 for s, _, _ in acct["events"] if s > step - w)
        for w in SUM_WINDOWS:
            feats[f"{role}_amount_sum_last_{w}h"] = sum(a for s, a, _ in acct["events"] if s > step - w)
        for w in NEWCP_WINDOWS:
            feats[f"{role}_new_counterparties_last_{w}h"] = sum(f for s, _, f in acct["events"] if s > step - w)
        return feats

    def compute_and_update(self, sender: str, dest: str, step: int, amount: float) -> dict:
        """Return past-only features for this event, THEN update the state with it."""
        is_new_pair = (sender, dest) not in self._pairs
        s_acct = self._state["sender"].setdefault(sender, self._new_account())
        d_acct = self._state["dest"].setdefault(dest, self._new_account())

        feats = {}
        feats.update(self._role_features("sender", s_acct, step))
        feats.update(self._role_features("dest", d_acct, step))
        feats["is_new_destination_for_sender"] = int(is_new_pair)
        feats["amount_vs_sender_hist_mean"] = safe_divide(amount, feats["sender_prev_mean_amount"])
        feats["amount_vs_dest_hist_mean"] = safe_divide(amount, feats["dest_prev_mean_amount"])

        for acct in (s_acct, d_acct):
            acct["count"] += 1
            acct["total"] += amount
            acct["max"] = amount if (isinstance(acct["max"], float) and math.isnan(acct["max"])) else max(acct["max"], amount)
            acct["last_step"] = step
            acct["uniq"] += int(is_new_pair)
            acct["events"].append((step, amount, int(is_new_pair)))
        self._pairs.add((sender, dest))
        return feats

    def account_count(self) -> dict:
        return {"sender_accounts_tracked": len(self._state["sender"]), "dest_accounts_tracked": len(self._state["dest"])}

    def preview_features(self, sender: str, dest: str, step: int, amount: float) -> dict:
        """Compute one feature state without consuming the event, for parity validation only."""
        state, pairs = self._state, self._pairs
        self._state, self._pairs = deepcopy(state), set(pairs)
        try:
            return self.compute_and_update(sender, dest, step, amount)
        finally:
            self._state, self._pairs = state, pairs


# One shared, process-wide state instance (see AccountState docstring for its scope/limitations).
account_state = AccountState()



def build_feature_vector(txn: "TransactionRequest", update_state: bool = True) -> pd.DataFrame:
    """
    Full pipeline: raw transaction -> candidate SAFE/POTENTIAL_RISK features -> exact Model V1
    feature names, in the exact expected order. Raises ValueError (-> HTTP 400) on any mismatch
    instead of silently reordering or dropping columns.
    """
    candidate = {}
    candidate.update(create_temporal_features(txn.step))
    candidate.update(create_amount_features(txn.amount, txn.oldbalanceOrg, txn.oldbalanceDest))
    candidate.update(create_balance_features(txn.oldbalanceOrg, txn.oldbalanceDest))
    state_features = (account_state.compute_and_update(txn.nameOrig, txn.nameDest, txn.step, txn.amount)
                      if update_state else account_state.preview_features(txn.nameOrig, txn.nameDest, txn.step, txn.amount))
    candidate.update(state_features)
    candidate.update(encode_transaction_type(txn.type))
    if RETAIN_FLAG_FEATURE:
        candidate["is_flagged_by_rule"] = int(txn.isFlaggedFraud or 0)

    missing = [f for f in FINAL_FEATURES if f not in candidate]
    if missing:
        raise ValueError(f"Feature mismatch: the model expects feature(s) the pipeline did not compute: {missing}. "
                         "Refusing to guess - check that app.py matches the current Phase 3/4 artifacts.")
    ordered = {f: candidate[f] for f in FINAL_FEATURES}          # exact name AND exact order
    return pd.DataFrame([ordered], columns=FINAL_FEATURES)


def assign_risk_level(score: float) -> str:
    for level, (lo, hi) in RISK_LEVELS.items():
        if lo <= score < hi or (level == "HIGH" and score >= hi):
            return level
    return "HIGH"


def predict_transaction(txn: "TransactionRequest") -> dict:
    """The full scoring function used by POST /predict."""
    X = build_feature_vector(txn)
    fraud_probability = float(model.predict_proba(X)[:, 1][0])
    predicted_label = int(fraud_probability >= CLASSIFICATION_THRESHOLD)
    risk_score = round(fraud_probability * 100, 4)               # Model-derived Risk Score (Phase 4 definition) - not independently calibrated
    risk_level = assign_risk_level(risk_score)
    return {"prediction": predicted_label, "fraud_probability": fraud_probability, "risk_score": risk_score,
            "risk_level": risk_level, "model_version": MODEL_VERSION}


def log_prediction(result: dict) -> None:
    """Lightweight local JSONL prediction log. Logs OUTPUTS only - no raw transaction fields,
    no isFraud. A later phase replaces this with a proper transaction store / streaming sink."""
    record = {"timestamp_utc": datetime.now(timezone.utc).isoformat(), "model_version": result["model_version"],
              "fraud_probability": result["fraud_probability"], "predicted_label": result["prediction"],
              "risk_score": result["risk_score"], "risk_level": result["risk_level"]}
    try:
        LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(LOG_PATH, "a", encoding="utf-8") as fh:
            fh.write(json.dumps(record) + "\n")
    except OSError as exc:                                        # logging must never break a prediction response
        logger.warning("Could not write prediction log: %s", exc)


# -----------------------------------------------------------------------------------------------
# Request schema. CRITICAL: `isFraud` does not appear here - the true label is never known at
# prediction time. newbalanceOrig/newbalanceDest are accepted (optional) only so a raw historical
# PaySim CSV row can be sent as-is for testing; the feature pipeline above never reads them.
# -----------------------------------------------------------------------------------------------

class TransactionRequest(BaseModel):
    step: int = Field(..., ge=1, description="Simulated hour of the transaction (PaySim: 1 step = 1 hour).")
    type: str = Field(..., description=f"Transaction type. One of: {TYPE_CATEGORIES}")
    amount: float = Field(..., ge=0, description="Transaction amount. Must be >= 0.")
    nameOrig: str = Field(..., min_length=1, description="Sender account identifier.")
    oldbalanceOrg: float = Field(..., ge=0, description="Sender balance BEFORE the transaction. Must be >= 0.")
    nameDest: str = Field(..., min_length=1, description="Destination account identifier.")
    oldbalanceDest: float = Field(..., ge=0, description="Destination balance BEFORE the transaction. Must be >= 0.")
    isFlaggedFraud: Optional[int] = Field(0, ge=0, le=1, description="Existing rule-based flag (0 or 1). Optional.")
    newbalanceOrig: Optional[float] = Field(None, description="Accepted for raw-row compatibility ONLY - NOT used by the model (post-transaction/leakage field, see Phase 3 leakage audit).")
    newbalanceDest: Optional[float] = Field(None, description="Accepted for raw-row compatibility ONLY - NOT used by the model (post-transaction/leakage field, see Phase 3 leakage audit).")

    @field_validator("type")
    @classmethod
    def _type_must_be_supported(cls, v: str) -> str:
        if v not in TYPE_CATEGORIES:
            raise ValueError(f"type must be one of {TYPE_CATEGORIES}, got {v!r}")
        return v

    model_config = {
        "extra": "forbid",   # CRITICAL: explicitly REJECTS any extra field (e.g. isFraud) with a 422, rather than silently ignoring it
        "json_schema_extra": {"example": {
            "step": 5, "type": "TRANSFER", "amount": 1500.0, "nameOrig": "C1234567890", "oldbalanceOrg": 5000.0,
            "nameDest": "C9876543210", "oldbalanceDest": 0.0, "isFlaggedFraud": 0}}}


class PredictionResponse(BaseModel):
    prediction: int
    fraud_probability: float
    risk_score: float
    risk_level: str
    model_version: str


# ---------------------------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------------------------
app = FastAPI(title="Financial Fraud Detection API", description="Serves Model V1 fraud predictions for the "
             "Adaptive Real-Time Financial Transaction Fraud Detection System.", version=MODEL_VERSION)


@app.get("/")
def root():
    return {"service": "Financial Fraud Detection API", "status": "running", "model_version": MODEL_VERSION}


@app.get("/health")
def health():
    return {"status": "healthy", "model_loaded": model is not None, "model_version": MODEL_VERSION}


@app.post("/state/reset")
def reset_state():
    """Development-only reset for deterministic historical replay before Phase 6."""
    account_state.reset()
    return {"status": "reset", "account_state": account_state.account_count()}


@app.post("/state/warmup")
def warmup_state(transactions: list[TransactionRequest]):
    """Replay pre-live transactions into AccountState without model prediction or logging."""
    for txn in transactions:
        account_state.compute_and_update(txn.nameOrig, txn.nameDest, txn.step, txn.amount)
    return {"status": "warmed", "processed_transactions": len(transactions),
            "account_state": account_state.account_count()}

@app.post("/state/preview")
def preview_state(txn: TransactionRequest):
    """Return the exact Model V1 feature vector without consuming the transaction."""
    row = build_feature_vector(txn, update_state=False).iloc[0]
    features = {name: (None if pd.isna(value) else float(value)) for name, value in row.items()}
    return {"features": features,
            "feature_names": FINAL_FEATURES}


@app.post("/predict", response_model=PredictionResponse)
def predict(txn: TransactionRequest):
    try:
        result = predict_transaction(txn)
    except ValueError as exc:                                     # feature mismatch - our own guard above
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:                                      # unexpected - never leak internals to the client
        logger.exception("Unexpected error during prediction")
        raise HTTPException(status_code=500, detail="Internal error while generating a prediction.") from exc
    log_prediction(result)
    return result
